hue:
  user: cdKjsOQIRY8hFXV5aNS8rb6JePNkik8hnmx-WMsn
  scenes:
    sunstatus:
      enabled: true
      id: 93yv8JekmAneCU9
      group: 1
    disable:
      enabled: true
      id: 93yv8JekmAneCU9
      group: 6
